#!/bin/sh
#
#  Copyright (C) 2010 Mike Gerwitz
#
#  This file is part of ease.js.
#
#  ease.js is free software: you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free
#  Software Foundation, either version 3 of the License, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful, but WITHOUT
#  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
#  for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
# #

PATH_TOOLS=$( dirname "$0" )/../tools

# string to remove trailing commas from
TEST_DATA=$( echo '[a,b,]{a,b,}[
    a,
    b,
    ]{
    a,
    b,
    }' \
    | $PATH_TOOLS/rmtrail
)

# expected result
TEST_CMP='[a,b]{a,b}[
    a,
    b
    ]{
    a,
    b
    }'

# perform the assertion
if [ ! "$TEST_DATA" == "$TEST_CMP" ]; then
    echo "rmtrail failed"
    echo "< expected"
    echo "> given"

    diff <( echo "$TEST_CMP" ) <( echo "$TEST_DATA" )
    exit 1
fi

exit 0

