#!/bin/bash
#
#  Copyright (C) 2010, 2011, 2013, 2014 Free Software Foundation, Inc.
#
#  This file is part of GNU ease.js.
#
#  ease.js is free software: you can redistribute it and/or modify it under
#  the terms of the GNU General Public License as published by the Free
#  Software Foundation, either version 3 of the License, or (at your option)
#  any later version.
#
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
#  Public License for more details.
#
#  You should have received a copy of the GNU General Public License along
#  with this program.  If not, see <http://www.gnu.org/licenses/>.
# #

PATH_TOOLS=$( dirname "$0" )/../tools

# string to remove trailing commas from
TEST_DATA=$( echo '[a,b,]{a,b,}[
    a,
    b,
    ]{
    a,
    b,
    }
    [c, // comment]
    [d, //comment
    ]
    [e,// comment]' \
    | $PATH_TOOLS/rmtrail
)

# expected result
TEST_CMP='[a,b]{a,b}[
    a,
    b
    ]{
    a,
    b
    }
    [c // comment]
    [d //comment
    ]
    [e// comment]' \

# perform the assertion
if [ ! "$TEST_DATA" == "$TEST_CMP" ]; then
    echo "rmtrail failed"
    echo "< expected"
    echo "> given"

    diff <( echo "$TEST_CMP" ) <( echo "$TEST_DATA" )
    exit 1
fi

exit 0

