#!/bin/bash
#
# Simple parser for static HTML generation
#
#  Copyright (C) 2010 Mike Gerwitz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

curver="$( git tag -l | tail -n1 )"

# TODO: Both sed and gawk are unnecessary; it was just the most convenient
# solution
gawk '
  match( $0, /^ *<!--%inc (.*?) *--> *$/, arr ) {
    system( "cat " arr[1] )
    next
  }
  { print }
' \
  | sed 's/<!--%curver-->/'$curver'/g'
