#!/bin/sh
# Generates version string
#
#  Copyright (C) 2014 Free Software Foundation, Inc.
#
#  This file is part of GNU ease.js.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# for distributions
if [ -s version ]; then
  cat version
  exit
fi

git rev-parse --show-toplevel >/dev/null 2>&1 || {
  echo 'fatal: git repository is not available'
}

version="$( git describe --match='[0-9]\.*' --abbrev=7 HEAD 2>/dev/null )"
git update-index -q --refresh
test -z "$( git diff-index --name-only HEAD)" || version="$version-dirty"

echo -n "$version"

