#!/bin/bash
#
# Simple version update script
#
#  Copyright (C) 2012, 2013 Mike Gerwitz
#
#  This file is part of GNU ease.js.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

major="$1"
minor="$2"
rev="$3"
suffix="${4:+-$4}"

version="$major.$minor.$rev$suffix"

# pre-formatted suffix
fsuffix=
[ -n "$suffix" ] && fsuffix="-$suffix"

# generate version.js
cat version.js.tpl | sed "
  s/@MAJOR@/$major/;
  s/@MINOR@/$minor/;
  s/@REV@/$rev/;
  s/@SUFFIX@/${suffix#-}/;
" > ../lib/version.js

# update configure script by replacing the second argument of AC_INIT
sed -i '/^AC_INIT/s/, \[[^]]\+\]/, ['$version']/' ../configure.ac
